name: Frontend Workshop Demo

on:

  push:

    branches:

      - 'feature/**'

      - 'bugfix/**'

      - 'hotfix/**'
      - main #อย่าลืมลบถ้าใช้ flow ปกติ

jobs:

  job-1:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
          cache: 'npm'
      - run: node -v


