name: Frontend Workshop Demo

on:

  push:

    branches:

      - 'feature/**'

      - 'bugfix/**'

      - 'hotfix/**'
      - main #อย่าลืมลบถ้าใช้ flow ปกติ

jobs:

  job-1:

    runs-on: ubantu-latest

    steps:

      - run: echo "Hello World"


