name: Frontend Workshop Demo

on:

  push:

    branches:

      - 'feature/**'

      - 'bugfix/**'

      - 'hotfix/**'
      - main #อย่าลืมลบถ้าใช้ flow ปกติ

  pull_request:
    branches:
      - main

jobs:

  lint-job:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - run: npm ci #clean install แทน npm install
      - run: npm run lint #ตรวจสอบโค้ด

 
  build-job:
    runs-on: ubuntu-latest
    needs: lint-job #รอให้ lint-job ทำงานเสร็จก่อน
    steps:
      - name: Clone Repo 
        uses: actions/checkout@v6
      - name: Setup Node.js version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci #clean install แทน npm install
      - name: Build Project
        run: npm run build #สร้างโปรเจกต์

